-- MySQL Script generated by MySQL Workbench
-- Mon May  6 20:35:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NighAppDB1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `NighAppDB1` ;

-- -----------------------------------------------------
-- Schema NighAppDB1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NighAppDB1` DEFAULT CHARACTER SET utf8 ;
USE `NighAppDB1` ;

-- -----------------------------------------------------
-- Table `NighAppDB1`.`tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NighAppDB1`.`tests` ;

CREATE TABLE IF NOT EXISTS `NighAppDB1`.`tests` (
  `idtable1` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `testValue` VARCHAR(45) NULL DEFAULT 'testVal',
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NighAppDB1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NighAppDB1`.`users` ;

CREATE TABLE IF NOT EXISTS `NighAppDB1`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `createDatetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NighAppDB1`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NighAppDB1`.`events` ;

CREATE TABLE IF NOT EXISTS `NighAppDB1`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DECIMAL(10,6) NOT NULL,
  `longitude` DECIMAL(10,6) NOT NULL,
  `createDatetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(280) NULL DEFAULT NULL,
  `category` VARCHAR(45) NOT NULL DEFAULT 'GENERAL',
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDING',
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `eventsUserId`
    FOREIGN KEY (`userId`)
    REFERENCES `NighAppDB1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NighAppDB1`.`accepts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NighAppDB1`.`accepts` ;

CREATE TABLE IF NOT EXISTS `NighAppDB1`.`accepts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(280) NULL,
  `createDatetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userId` INT NOT NULL,
  `eventId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `acceptsUserId`
    FOREIGN KEY (`userId`)
    REFERENCES `NighAppDB1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `acceptsEventId`
    FOREIGN KEY (`eventId`)
    REFERENCES `NighAppDB1`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;